name: all-contributors

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: "* 0 * * *"

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        uses: milvus-io/hero-bot@1.11
        with:
          # Required
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}
          repos: "towhee-io/towhee, towhee-io/examples"
          target: "towhee-io/towhee/README.md"
          # Optional
          isAscend: True
          width: "30px"

      - name: Update README_CN
        uses: milvus-io/hero-bot@1.11
        with:
          # Required
          token: ${{ secrets.ALL_CONTRIBUTORS_TOKEN }}
          repos: "towhee-io/towhee, towhee-io/examples"
          target: "towhee-io/towhee/README_CN.md"
          # Optional
          isAscend: True
          width: "30px"