name: Check Towhee docs update

on:
  push:
    branches:
      - 'branch0.8.1'
    paths:
      - "docs/**"

jobs:
  dispatch-update:
    runs-on: "ubuntu-latest"
    steps:
      - name: Trigger docs.towhee.io rebuild
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'towhee-io',
              repo: 'towhee-docs',
              workflow_id: 'publish.yaml',
              ref: 'main',
            });
          debug: true
        